### ISSUE TITLE
rdap.lacnic.net is still agressively rate limiting

### ISSUE THREAD

**Issue by secynic** [secynic/ipwhois#104]
While LACNIC RDAP says "Rate Limit is maxed at 10 queries per 1 minutes.", I am getting far fewer than 10 queries in. Tested from several networks. I am testing with pure wget at this point (no ipwhois code). My very first query from a dedicated VPS IP resulted in the rate limit error.

If anyone has the spare cycles, I could use help testing this and also figuring out how long the temp ban lasts.

**Comment by imaia** [comment]
I'm having this same issue. Whois has approach to work around this issue, where you consult ip addresses in batch. Is there a way to do the same with ipwhois?

**Comment by secynic** [comment]
The only RDAP batch lookups I know of are per user request e.g., LACNIC: http://www.lacnic.net/documents/10834/1535064/solicitud-rdap-beta-en.pdf

I can't do this at the library level obviously, each user/org would need to request it.

The real problem still lies on their rate limiting bug.

**Comment by secynic** [comment]
I reached out to lacnic, will report back.

**Comment by secynic** [comment]
No response yet, trying some additional contacts.

**Comment by secynic** [comment]
I got a response and am working with LACNIC to help troubleshoot the issue.

**Comment by secynic** [comment]
Lacnic responded that they fixed the problem. Everything appears to be working again. I will leave this open while I run tests for 0.13.0.
