### ISSUE TITLE
Error with obj.lookup_whois

### ISSUE THREAD

**Issue by jstnk9** [secynic/ipwhois#130]
Hello, i have a error with the function lookup_whois.

my code is 

```
obj = IPWhois('191.5.59.19')
		
		results = obj.lookup_whois()

		
		
```
but results returns nothing. Why?

**Comment by secynic** [comment]
Working for me. Some questions: 
- Are you getting any errors? Can you paste what is returned/raised?
- What version of Python and ipwhois are you using?
- Are you performing bulk queries?
- Is that same method working for other IPs?

Thanks.

**Comment by jstnk9** [comment]
@secynic Hello!
I'm working with threads (Threading) and i'm losing threads on that function (obj.lookup_whois()).

i'm doing so much queries (5.000 more or less) What can i do? 


Thanks

**Comment by secynic** [comment]
What errors are you getting? 

"The timeout not found" - Are you getting RateLimitError?

**Comment by secynic** [comment]
Any update? Did you resolve your issue?

**Comment by secynic** [comment]
Closing due to no response, and I could not replicate the issue. If you are still having this issue, please re-open and provide as much debug info as possible.
