### ISSUE TITLE
Update ES and redis examples

### ISSUE THREAD

**Issue by secynic** [secynic/ipwhois#138]
Update ES and redis examples to new output format.

**Comment by simathur** [comment]
It would be great if the ES example would allow an AWS ElasticSearch service (includes Kibana) endpoint to be configured. 
https://aws.amazon.com/elasticsearch-service/
I was able to configure AWS ES 2.x family instance OK with the script after editing host+port defaults, but had issues with kexport/kimport working for Kibana configuration.

**Comment by secynic** [comment]
I will definitely look into this. Can you provide any errors/debug you are seeing with kexport/kimport? 

Those are pretty simple implementations. I wonder if it is just a matter of updating to the latest ES schema.

Thanks.

**Comment by secynic** [comment]
Merged in #192
