### ISSUE TITLE
restfulwhoisv2.labs.lacnic.net down

### ISSUE THREAD

**Issue by jumoog** [secynic/ipwhois#141]
http://restfulwhoisv2.labs.lacnic.net/restfulwhois/ip/

moved to https://rdap.db.ripe.net/ip/

**Comment by secynic** [comment]
That old labs.lacnic.net URL was changed to rdap.lacnic.net a while ago. Can you verify your ipwhois version is up to date? Just ran some tests, all passing.

**Comment by jumoog** [comment]
im using pip

**Comment by secynic** [comment]
Can you run pip show ipwhois? If that doesn't show 0.14.0, try pip install --upgrade ipwhois

**Comment by jumoog** [comment]
thanks
