### ISSUE TITLE
Handling rate-limiting via status code 429

### ISSUE THREAD

**Issue by rikonor** [secynic/ipwhois#144]
Continuing from https://github.com/secynic/ipwhois/pull/143, when RIPE rate-limits, it returns a generic html page and status code 429, rather then the expected JSON.
Therefore on request failure the status code should be checked for as well.

Regarding your previous question about the point at which they start rate-limiting, I think it's around ~3500 requests. I'm not sure for how long the block persists.

**Comment by secynic** [comment]
Oh wow. At least it isn't bad like Lacnic's 10 requests per minute. I'm going to write some tests for this and the other RIRs as well, but they won't be included in Travis builds, as I don't want to spam the RIRs on every commit.

**Comment by rikonor** [comment]
Sounds good. Thanks for answering this so quick - appreciate it.

**Comment by secynic** [comment]
Merged in #145. Leaving this open pending new offline rate limit tests.

**Comment by rikonor** [comment]
Hey @secynic thanks for fixing the RIPE rate-limiting issue. It's been working pretty great.

I've started noticing something else recently.
When querying LACNIC via the legacy WHOIS, when you get rate-limited the client will just hang there. Is there a way to make it fail with a RateLimitError by tweaking some of the method params?

**Comment by secynic** [comment]
Good to hear the fix is working.

Is the legacy issue all RIRs or just RIPE again?

**Comment by rikonor** [comment]
Hey @secynic, as far as I could tell, LACNIC is the only RIR where I encounter this behavior. That said, they are also the only ones that will limit you after 10 requests.

**Comment by secynic** [comment]
I think they must have changed the Whois response. 

Legacy whois (Net.get_whois()) does check for rate limit: 
https://github.com/secynic/ipwhois/blob/master/ipwhois/net.py#L572

Let me run some tests.

**Comment by secynic** [comment]
Hmm think I found it, looks like another bug (infinite recursive loop - or until rate-limit ban is lifted). 

I have retry_count checks in exception handling, but not prior to the first recursive get_whois call. Should be an easy fix.

**Comment by secynic** [comment]
Please test the dev branch, it should be fixed.

**Comment by rikonor** [comment]
Hey @secynic, left you a comment on https://github.com/secynic/ipwhois/commit/9d97f65d16535b9d7160f9313950214b7ee9aa57#commitcomment-19740116

**Comment by secynic** [comment]
Thanks, fixed

**Comment by secynic** [comment]
Have you had a chance to test this? If all is good on your end, I will merge.

**Comment by rikonor** [comment]
@secynic Yep, works great. Thanks for the fix.
Only tested with LACNIC, though. Haven't gotten rate-limited by the others so far.

**Comment by secynic** [comment]
Thanks for testing. Merged in 343f944ba174c9be57caa534b4fbf72e4fa57882

Still leaving open for previous mentioned offline tests. I also lost 100% coverage on this merge, need to add a test for WhoisRateLimitError.

**Comment by secynic** [comment]
I just wanted to provide an update given the amount of time that has passed. I have been busier than usual with work/life/holidays, and plan to get 0.15.0 pushed to PyPi soon. 

The only items pending are these offline tests and #149.

Sorry for the delay!

**Comment by rikonor** [comment]
Understood, thank you for the update!
