### ISSUE TITLE
Bootstrap not working

### ISSUE THREAD

**Issue by droravr** [secynic/ipwhois#148]
Maybe I'm missing something but when I activate bootstrap i get:
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pycharm\utrunner.py", line 153, in <module>
    modules = [loadSource(a[0])]
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pycharm\utrunner.py", line 65, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "C:\Users\davrahami\PycharmProjects\research_scripts\Analysis\Modules\checks.py", line 9, in <module>
    r = c.lookup_rdap(bootstrap=True)
  File "C:\Python27\lib\site-packages\ipwhois\ipwhois.py", line 288, in lookup_rdap
    if 'JP' == asn_data['asn_country_code']:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by secynic** [comment]
When you use bootstrap=True, it will bypass ASN lookups (setting those asn_* result keys to None), and use ARIN's bootstrap server:
https://ipwhois.readthedocs.io/en/v0.14.0/RDAP.html#bootstrap

If you still need ASN data later, you can call Net.lookup_asn() directly:
https://github.com/secynic/ipwhois/blob/master/ipwhois/net.py#L818

Basically, bootstrap is there if you don't need the ASN data and want faster RDAP whois results.

**Comment by pvkc** [comment]
Hi, I'm trying to use IPWhoIs with `bootstrap=True`. I get the following error. Could you tell how to use IPWhoIs with `bootstrap=True`
```
In [30]: IPWhois('1.1.1.1').lookup_rdap(bootstrap=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-0a953a57bf36> in <module>
----> 1 IPWhois('1.1.1.1').lookup_rdap(bootstrap=True)

/usr/local/lib/python3.7/site-packages/ipwhois/ipwhois.py in lookup_rdap(self, inc_raw, retry_count, depth, excluded_entities, bootstrap, rate_limit_timeout, asn_alts, extra_org_map, inc_nir, nir_field_list, asn_methods, get_asn_description)
    328
    329             nir = None
--> 330             if 'JP' == asn_data['asn_country_code']:
    331                 nir = 'jpnic'
    332             elif 'KR' == asn_data['asn_country_code']:

TypeError: 'NoneType' object is not subscriptable
```
