### ISSUE TITLE
Problem with IP from KR

### ISSUE THREAD

**Issue by th3V** [secynic/ipwhois#150]
from ipwhois import IPWhois
ip = '1.209.148.1'
obj = IPWhois( str(ip) )
res=obj.lookup_whois()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../src/ipwhois/ipwhois/ipwhois.py", line 184, in lookup_whois
field_list=nir_field_list, is_offline=False
  File "/.../src/ipwhois/ipwhois/nir.py", line 497, in lookup
form_data=form_data
  File "/.../src/ipwhois/ipwhois/net.py", line 977, in get_http_raw
request_type=request_type, form_data=form_data
  File "/.../src/ipwhois/ipwhois/net.py", line 931, in get_http_raw
form_data = urlencode(form_data)
  File "/usr/lib/python2.7/urllib.py", line 1324, in urlencode
raise TypeError
TypeError: not a valid non-string sequence or mapping object

res=obj.lookup_whois( retry_count=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../src/ipwhois/ipwhois/ipwhois.py", line 184, in lookup_whois
    field_list=nir_field_list, is_offline=False
  File "/.../src/ipwhois/ipwhois/nir.py", line 497, in lookup
    form_data=form_data
  File "/.../src/ipwhois/ipwhois/net.py", line 983, in get_http_raw
    url))
ipwhois.exceptions.HTTPLookupError: HTTP lookup failed for http://whois.kisa.or.kr/eng/whois.jsc.

**Script whois.jsc on http://whois.kisa.or.kr/eng/ doesn't exist.**

**Comment by secynic** [comment]
Strange, it is working fine for me. Can you hit http://whois.kisa.or.kr/eng in your browser? 

Here is the output from testing it:
```python
from ipwhois import IPWhois
from pprint import pprint
pprint(IPWhois('1.209.148.1').lookup_whois())
{'asn': '3786',
 'asn_cidr': '1.208.0.0/12',
 'asn_country_code': 'KR',
 'asn_date': '2010-06-11',
 'asn_registry': 'apnic',
 'nets': [{'address': 'Seoul Songpa-gu Jungdae-ro 135',
           'cidr': '1.208.0.0/12',
           'city': None,
           'country': 'KR',
           'created': None,
           'description': 'BORANET\n'
                          '65-228,DACOM Bldg ,Hangangro 1ga Yongsangu, Seoul\n'
                          '****************************************\n'
                          'Allocated to KRNIC Member.\n'
                          'If you would like to find assignment\n'
                          'information in detail please refer to\n'
                          'the KRNIC Whois Database at:\n'
                          'http://whois.nic.or.kr/english/index.htm\n'
                          '*****************************************',
           'emails': ['hm-changed@apnic.net',
                      'hostmaster@nic.or.kr',
                      'ipadm@lguplus.co.kr',
                      'hostmast@nic.or.kr'],
           'handle': 'IM148-AP',
           'name': 'BORANET',
           'postal_code': None,
           'range': '1.208.0.0 - 1.223.255.255',
           'state': None,
           'updated': '20150310'},
          {'address': None,
           'cidr': '1.208.0.0/12',
           'city': None,
           'country': 'KR',
           'created': None,
           'description': 'LG DACOM Corporation',
           'emails': ['hostmaster@nic.or.kr'],
           'handle': None,
           'name': 'BORANET-KR',
           'postal_code': None,
           'range': '1.208.0.0 - 1.223.255.255',
           'state': None,
           'updated': None}],
 'nir': {'nets': [{'address': 'Seoul Yongsan-gu Hangang-daero',
                   'cidr': '1.208.0.0/12',
                   'contacts': {'admin': {'email': 'ipadm@lguplus.co.kr',
                                          'name': 'IP Manager',
                                          'phone': '+82-2-6928-3087'},
                                'tech': None},
                   'country': 'KR',
                   'created': '2010-06-14T00:00:00',
                   'handle': 'BORANET',
                   'name': 'LG DACOM Corporation',
                   'nameservers': None,
                   'postal_code': '04389',
                   'range': '1.208.0.0 - 1.223.255.255',
                   'updated': None},
                  {'address': 'Gyeonggi-do Manan-gu, Anyang-si Deokcheon-ro 37',
                   'cidr': '1.209.148.0/24',
                   'contacts': {'admin': None,
                                'tech': {'email': 'b8273338@user.bora.net',
                                         'name': 'IP Manager',
                                         'phone': '+82-2-2089-7750'}},
                   'country': 'KR',
                   'created': '2012-04-19T00:00:00',
                   'handle': 'CUSTOMER',
                   'name': 'LG Uplus',
                   'nameservers': None,
                   'postal_code': '14088',
                   'range': '1.209.148.0 - 1.209.148.255',
                   'updated': None}],
         'query': '1.209.148.1',
         'raw': None},
 'query': '1.209.148.1',
 'raw': None,
 'raw_referral': None,
 'referral': None}
```

**Comment by th3V** [comment]
Yes I can open it <a href="http://imgur.com/a/6hrMc">print screen</a>.

**Comment by th3V** [comment]
OK, sorry it's my fault :) - f... firewall/iptables. THX

**Comment by secynic** [comment]
Glad you got it sorted out. Thanks for the follow-up.

**Comment by th3V** [comment]
thx but i write script and I get error with IP :) for make sure now I
disable firewall but still get this error.

>>> from ipwhois import IPWhois
>>> from pprint import pprint
>>> pprint(IPWhois('114.160.199.0').lookup_whois())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robo/src/ipwhois/ipwhois/ipwhois.py", line 184, in
lookup_whois
    field_list=nir_field_list, is_offline=False
  File "/home/robo/src/ipwhois/ipwhois/nir.py", line 591, in lookup
    dt_format=dt_format
  File "/home/robo/src/ipwhois/ipwhois/nir.py", line 424, in _get_contact
    request_type=NIR_WHOIS[nir]['request_type']
  File "/home/robo/src/ipwhois/ipwhois/net.py", line 964, in get_http_raw
    ''.format(url))
ipwhois.exceptions.HTTPLookupError: HTTP lookup failed for
http://whois.nic.ad.jp/cgi-bin/whois_gw?lang=%2Fe&key=KK551JP
TT15086JP
TT10660JP&submit=query.
>>>

Could you check it? Please.

2016-12-16 10:12 GMT+01:00 Philip Hane <notifications@github.com>:
