### ISSUE TITLE
ES 5.0 compatibility

### ISSUE THREAD

**Issue by s8mathur** [secynic/ipwhois#171]
First off, thanks for the very handy tools. 
The script fails at setup time due to the changes in geo_point and indices in ES 5.0 , so some small updates are needed. 
https://www.elastic.co/blog/elasticsearch-5-0-0-released

**Comment by secynic** [comment]
Thanks. This is partially tied to #138

**Comment by secynic** [comment]
Closing. I will track this in the aforementioned issue.
