### ISSUE TITLE
How are RDAP lookup and IP ASN lookup different in regards to retrieving ASN?

### ISSUE THREAD

**Issue by ZaneHintzman** [secynic/ipwhois#190]
The documentation for ipwhois says that IPWhois.lookup_rdap() is now the recommended lookup method, so I assumed this was the only way to get the correct ASN. I also notice there's separate IP ASN lookup functionality. On the Linux machines where I use ipwhois, I noticed that ASN lookups are much faster with the IP ASN lookup functionality than with RDAP. However, there are a number of IPs where the ASN returned is different between the two methods. For example, for the following IPs, these were the results:

- 223.100.157.219:
    - RDAP: 56044
    - ASN lookup: 9808
- 119.141.24.44:
    - RDAP: 134772
    - ASN lookup: 4134

How are these two methods different? Which one correctly returns the current ASN? I'm using version 0.15.1 of ipwhois, Python version 2.7.

Off-topic question: Is there a contact where I can send questions like this in the future? I didn't see any on the Contributing page.

**Comment by secynic** [comment]
IPWhois.lookup_rdap() is just a wrapper that used IPASN.lookup(). This is a bug, give me a bit to dig more.

If you run one of those multiple times, sometimes the ASN will flip. Cymru may be returning multiple or varying results I need to account for.

56044 is for 223.100.0.0/16
9808 is for 223.96.0.0/12

For questions, I am ok with issue submissions. I am also usually idle on freenode IRC in #python and #python-dev (I will add this to the contributing page).

Thanks for reporting this.

**Comment by secynic** [comment]
net.Net.get_asn_dns() needs to be modified to return the entire result, since the Cymru DNS query returns multiple results in no particular order. Then asn.IPASN.lookup() needs to figure out which of those results is the smallest CIDR, and use that one. 

I might consider changing the ASN return results for IPASN and IPWhois lookups in a post 1.0.0 release (to return multiple ASN results in a list).

**Comment by secynic** [comment]
Merged in #191

**Comment by JohnDoee** [comment]
As far as I understood the changelog, this does not seem to be fixed completely, at least.

    >>> obj = IPWhois('191.97.49.0')
    >>> results = obj.lookup_rdap(depth=1)
    2018-10-03 09:53:15+0000 DEBUG    ASN lookup for 191.97.49.0
    2018-10-03 09:53:15+0000 DEBUG    ASN query for 0.49.97.191.origin.asn.cymru.com
    2018-10-03 09:53:15+0000 DEBUG    ASN verbose query for AS28032 262589.asn.cymru.com
    2018-10-03 09:53:15+0000 DEBUG    ASN DNS verbose lookup failed: ASN lookup failed (DNS NXDOMAIN) for AS28032 262589.


It tries to resolve the domain `AS28032 262589.asn.cymru.com` and not taking multiple ASNs into consideration.
