### ISSUE TITLE
All errors use Exception as a base class, preventing succinct error handling

### ISSUE THREAD

**Issue by frankwoodall** [secynic/ipwhois#213]
# Problem
Because all of your exceptions inherit directly from the Exception class, it's impossible to write a small exception handler for your library. As it stands, I'm forced to either handle each exception explicitly or catch `Exception` directly -- both of which are undesirable. 

I suggest something like this:
```python

class IPWhoisException(Exception):
    pass


class NetError(IPWhoisException):
    """
    An Exception for when a parameter provided is not an instance of
    ipwhois.net.Net.
    """


class IPDefinedError(IPWhoisException):
    """
    An Exception for when the IP is defined (does not need to be resolved).
    """

# ... etc ...
```

Which would then allow me to do this:

```python

try:
    # ipwhois lookup
except IPWhoisException:
    # handle it
```

Thanks

**Comment by secynic** [comment]
This is fixed in the dev branch. See here:
https://github.com/secynic/ipwhois/issues/205
