### ISSUE TITLE
Issues Installing

### ISSUE THREAD

**Issue by Arkanyus** [secynic/ipwhois#240]
![image](https://user-images.githubusercontent.com/50503742/60051390-cc7fd280-96ca-11e9-9a05-fd63e4c9442e.png)

**Comment by secynic** [comment]
ipwhois isn't a binary. You would need to run /path/to/python /path/to/ipwhois/ipwhois_cli.py or import it. It looks like you are using python 2 with that pip command. Can you provide more information about your environment?

**Comment by secynic** [comment]
@Arkanyus Have you resolved your issue?

**Comment by Arkanyus** [comment]
I have not – I’ve been removing the ipwhois import and using without

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Arkanyus** [comment]
Using python3 and Ubuntu

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Ryan Kane
Sent: Wednesday, August 7, 2019 3:10:43 AM
To: secynic/ipwhois <reply@reply.github.com>
Subject: RE: [secynic/ipwhois] Issues Installing (#240)

I have not – I’ve been removing the ipwhois import and using without

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by secynic** [comment]
Can you try installing with pip3 instead?

**Comment by secynic** [comment]
Let me know if this still doesn't work. I think your issue was having multiple Python versions installed.
