### ISSUE TITLE
KRNIC parsing issues

### ISSUE THREAD

**Issue by Haruny-7577** [secynic/ipwhois#245]
contact field is
'IP Manager\n'
'Phone              : +82-2-1060-1060\n'
'E-Mail             : ip-adm@skbroadband.com\n'

but result is
 'contacts': {'admin': {'email': 'ip-adm@skbroadband.com'},
                                'tech': None},
my edited code result
 'contacts': {'admin': {'email': 'ip-adm@skbroadband.com',
                                          'name': 'IP Manager',
                                          'phone': '+82-2-1060-1060'},
                                'tech': None}

**Comment by secynic** [comment]
@Haruny-7577 What IP were you testing? KRNIC was broken, and is fixed in the dev branch. Can you try the dev branch?

**Comment by nikswap** [comment]
I got the following from KRNIC: ssl.CertificateError: hostname '후이즈검색.한국' doesn't match either of 'whois.kisa.or.kr', 'whois.nic.or.kr', 'whois.kr', 'xn--c79as89aj0e29b77z.xn--3e0b707e', 'xn--c79as89aj0e29b77z.kr' 

IP: 61.76.28.174

**Comment by elindsey** [comment]
My krnic parsing issues were fixed by switching to the dev branch - thanks for pointing out that the bugfix was there @secynic.
