### ISSUE TITLE
Question: is there a way to use ipwhois to parse WHOIS records from a file?

### ISSUE THREAD

**Issue by mpenkov** [secynic/ipwhois#248]
I've already retrieved some WHOIS records and stashed them in a file. Now I want to parse them (without retrieving them again).

Is there a way to access the WHOIS parser via the ipwhois API?

**Comment by secynic** [comment]
You can pass the response arg like in the offline tests: https://github.com/secynic/ipwhois/blob/master/ipwhois/tests/test_rdap.py#L26
https://github.com/secynic/ipwhois/blob/master/ipwhois/tests/test_rdap.py#L37

Keeping this open to document it.
