### ISSUE TITLE
WHOIS block

### ISSUE THREAD

**Issue by Huji** [secynic/ipwhois#251]
I was debugging a code that uses this package and in doing so, I ran a couple hundred IP WHOIS requests. This resulted in RIPE temporarily blocking my IP because I had surpassed RIPE's daily quota. In the python code, that resulted in the code just hanging (I learned about the RIPE block by running a `whois` command at the terminal and seeing the error message returned by RIPE).

The correct response in a situation like this should be an exception being thrown by the `ipwhois` package, not just leaving the user hanging.

**Comment by secynic** [comment]
Can you provide more details on the query tested, traceback, etc. This shouldn't be the case.

**Comment by Huji** [comment]
I cannot provide a traceback; the code doesn't crash, it just hangs there.

I can create a test code, but that would be at the expense of being blocked by RIPE again so please give me some time on that.
