### ISSUE TITLE
WhoisRateLimitError - how many requests to block?

### ISSUE THREAD

**Issue by LucasGitDev** [secynic/ipwhois#265]
I am new to this area and I am testing an application that requests ASN several times during the day. I've been unable to request because of this error. How many requests can I use before taking a strike? What criterion is used?

**Comment by secynic** [comment]
The ASN origin query WhoisRateLimitError would be from radb.net. I don't think I have ever been rate limited using that service. How many queries are you making and in what timeframe?

**Comment by LucasGitDev** [comment]
1 request every 3 minutes, but after observing I decided to change the trigger point to have more information in less time
