### ISSUE TITLE
BOOTSTRAP_URL is changed and last support will be until end of Feb 2021

### ISSUE THREAD

**Issue by ikalyvas** [secynic/ipwhois#300]
We noticed that during bootstrap=True in lookup_rdap method, the queries returned slower than in the case without bootstrap. Perhaps it's the fact that the bootstrap_url has changed according to Arin webpage.

Quote from web:
The URL for Registration Data Access Protocol (RDAP) bootstrap queries has changed to https://rdap-bootstrap.arin.net/bootstrap. If you have queries that use our RDAP bootstrap server, please update your links. Note that the current URL, https://rdap.arin.net/bootstrap, will be supported for 90 days, and that support will end on 18 February, 2021. Please use this 90-day period to migrate to the new URL. After 90 days, the old URL (https://rdap.arin.net/bootstrap) will no longer be supported.

**Comment by secynic** [comment]
Updated in dev branch. Thanks.
