### ISSUE TITLE
ImportError: attempted relative import with no known parent package [install error]

### ISSUE THREAD

**Issue by zencharcoal** [secynic/ipwhois#312]
Likely this is related to something I did and not an issue with the project, but I am struggling a little bit. Consistently receiving the same error. I have researched and tweaked within the limits of my patience. And yet I know it is probably something simple as I don't see anyone else with this as an issue. Forgive my ignorance, please. 

Using Ubuntu 20.04 and python3. 
Uninstalled python2 / python2.7 during troubleshooting.

![image](https://user-images.githubusercontent.com/63509228/121697361-45051700-cacd-11eb-8169-65abfa4e648a.png)

**Comment by secynic** [comment]
You can't run these files directly. I would suggest starting with the example here:
https://ipwhois.readthedocs.io/en/latest/RDAP.html#basic-usage
