### ISSUE TITLE
IPWhois(addr).lookup() uses 100% cpu with python 3.4

### ISSUE THREAD

**Issue by mc3** [secynic/ipwhois#74]
I just noticed. No further investigation done.

**Comment by secynic** [comment]
This is expected default behavior for Python. You can use [psutil] (https://pypi.python.org/pypi/psutil) (Cross-platform) or [nice] (https://docs.python.org/3.4/library/os.html#os.nice) (Unix) to limit process priority if it is an issue where the OS is not managing process priority as expected.
