### ISSUE TITLE
High CPU usage while running regex

### ISSUE THREAD

**Issue by max0d41** [secynic/ipwhois#75]
The regex with the key `misc_emails` that is compiled in ipwhois.py:778 and used after that with `finditer` can cause very high CPU usage over a few seconds.

I could not find the bug so, since I don't need this field, I removed all the `misc_emails` regexes from `NIC_WHOIS` which solved the issue.

**Comment by secynic** [comment]
The library will use as much CPU as possible/OS allows. I answered a similar question here: https://github.com/secynic/ipwhois/issues/74

I am seeing major performance increases for RDAP in my latest commit to the dev branch. Please consider trying that branch, and switching to IPWhois.lookup_rdap() for more accurate results. The next official release should be in a couple of weeks.

**Comment by secynic** [comment]
I thought about this more and opened a new issue to add field exclusion support. Thanks for the info.

**Comment by max0d41** [comment]
Well, maybe it would be better to add field inclusion support. When `None` or something all values are assumed by default.
I rather know what I need than what is supported and I don't need.

**Comment by secynic** [comment]
Good point, will do. I may actually add both.
