### ISSUE TITLE
cymru is down, ipwhois permutation causes ourself to get blacklisted

### ISSUE THREAD

**Issue by FirefighterBlu3** [secynic/ipwhois#85]
o_o

we need a flag in Net() to avoid permutations.

CYMRU DNS is currently offline. because DNS is yielding timeout errors, lookup_asn() is retrying via other methods -- which gets us blacklisted (stalled lookups leading to timeouts) from the other services -- which now yields several minutes per each lookup before finally giving up.

we need to pass a use_dns_only to the ASN lookup so if cymru is down, we don't punish ourselves by quickly getting blacklisted due to trying alternate means of obtaining results.

**Comment by secynic** [comment]
Good catch. I hope to have time tomorrow to look over your PRs.

When you say blacklisted, is it a complete block or just rate restricted? Can you tell if it is permanent or temporary?

Thanks.

**Comment by FirefighterBlu3** [comment]
give me a bit of time to reconfigure my app and see if it was permanent. when i noticed, it was complete block, not RR. since dns was down, each lookup was then trying http/whois and they did a packet drop rather than reject which meant my connection stalled.

**Comment by FirefighterBlu3** [comment]
it's not permanent, my blacklist entry has been removed :)

**Comment by secynic** [comment]
Good news. I still can't get to their main site (haven't had a chance to test the ASN service). Looks like this was all caused by a DDoS on one of their other services:
http://seclists.org/nanog/2016/Jan/675

Time for them to get a DDoS mitigation service, seeing how many organizations, apps, and libraries depend on their services.

**Comment by secynic** [comment]
I added comments requesting minor changes to #87. 

I still need to review #88.

**Comment by secynic** [comment]
Added in c031c59
