### ISSUE TITLE
RDAP - No descr

### ISSUE THREAD

**Issue by didn0t** [secynic/ipwhois#91]
When querying RIPE the resulting network object doesn't include the inetnum's description (descr) field.

Looking at the Raw RDAP this field would appear to be in under remarks:

 "remarks" : [ {
    "description" : [ "Test" ]
  } ],

**Comment by secynic** [comment]
Can you provide more detail? Is it a bug in ipwhois output? RDAP changed result formatting, so if the data is in the raw RDAP results for remarks, it should be returned as such in the ipwhois results.

**Comment by didn0t** [comment]
The network object doesn't contain this information:

             'raw': None,
             'remarks': None,

This data came from RIPE.

**Comment by secynic** [comment]
Thanks. It was a bug when remarks didn't have a title value. Fix incoming shortly.

**Comment by secynic** [comment]
Fixed in 0.11.2
