### ISSUE TITLE
If AS Lookup fails Cyrmu DNS ability to still grab WhoIS and continue

### ISSUE THREAD

**Issue by neu5ron** [secynic/ipwhois#93]
First off, thanks for adding the allow_permutations if DNS in cyrmu fails.
But lets say I set allow_permutations to False (in order to not grab AS information via whois and only DNS) but the regular IP whois is successful---Is there a way you can set it so the whois data is still applied but AS Information is ignored and the script continues. Like an ability to set a variable such as allow_permutations_fail_continue=True (but by default =False)
then edit the block line 606 in "net.py"
if not self.allow_permutations and self.allow_permutations_fail_continue:
    return:
                asn_data = {
                    'asn_registry': None,
                    'asn': None,
                    'asn_cidr': None,
                    'asn_country_code': None,
                    'asn_date': None
                }
elif not self.allow_permutations and not self.allow_permutations_fail_continue:
    raise ASNRegistryError('ASN registry lookup failed. '
                                       'Permutations not allowed.')
Then continue script as normal

I am trying to write a script to pull the ASName & ASNumber from Maxminds GeoIP AS Database if this part fails, however the raise functions are not allowing me to grab the IP Whois and ignore AS.

Thanks for this awesome script.

**Comment by secynic** [comment]
Thanks for the kind words.

Yes, I believe I can do that for RDAP, since we have the bootstrap feature. I will look into it this weekend and post a more detailed response here.

For a short term workaround, take a look at https://github.com/secynic/ipwhois/blob/master/ipwhois/tests/online/test_rdap.py. You can directly perform lookups to rdap.RDAP.lookup() and skip the ASN lookups by setting the bootstrap parameter to True.

**Comment by secynic** [comment]
Update: I can add a whitelist parameter (e.g., asn_lookups) to Net.lookup_asn() and the calls from IPWhois.lookup() and IPWhois.lookup_rdap() with an array value like ['dns', 'whois', 'http']. For RDAP, it will continue on ASN lookup failure if the bootstrap parameter is true. For legacy whois, it will fail if ASN info can't be retrieved.

Sorry for the delayed response.

**Comment by neu5ron** [comment]
No worries at all regarding delayed response. Cant imagine releasing code
that is used by many people, almost may feel like helpdesk sometimes (I
have been there).

That sounds good.
So in other words I would pass in whatever I want to whitelist (in this
case dns) and so then whois data would still be returned?

If that is the case then essentially in my script I will just try dns and
whois then catch AS exception and if exception caught then try and return
whois (if no exception)----That will be easy if so, I essentially already
implemented that (except if there was an error then I just skipped Whois
completely and grabbed AS Name+Number from Maxmind GeoIP DBs).

**Comment by neu5ron** [comment]
Maybe I can work on a pull request too, that is what I should have done in
the first place.. sorry about that, I am only recent in sharing github
repos vs using just my own (so learning fork, pull, merge, etc etc etc).

**Comment by secynic** [comment]
Correct. You would be telling the ASN lookup which types of queries are allowed (asn, whois, http). I should be able to get this added quickly, as I already know what changes need to be done. I welcome any contributions, just read over [CONTRIBUTING](https://github.com/secynic/ipwhois/blob/master/CONTRIBUTING.rst) first.

Thanks.

**Comment by secynic** [comment]
Pushed to dev. Will merge with 0.12.0
