### ISSUE TITLE
Lookup Stalls and Fails for 191. Networks

### ISSUE THREAD

**Issue by robertjuric** [secynic/ipwhois#94]
When I run a script against a list of netflow entries, addresses in the 191 network stall my script, when I kill it I see a WHOIS lookup failed.
````
File "whois.py", line 44, in <module>
    results = obj.lookup()
File "/usr/local/lib/python2.7/site-packages/ipwhois/ipwhois.py", line 125, in lookup
    ignore_referral_errors, asn_data, field_list
File "/usr/local/lib/python2.7/site-packages/ipwhois/whois.py", line 554, in lookup
    extra_blacklist=extra_blacklist)
File "/usr/local/lib/python2.7/site-packages/ipwhois/net.py", line 468, in get_whois
    'WHOIS lookup failed for %r.' % self.address_str
ipwhois.exceptions.WhoisLookupError: WHOIS lookup failed for '191.234.210.42'
````

**Comment by secynic** [comment]
I am not able to replicate this issue. Lookups should never stall indefinitely, given the built in timeouts. Is it working for other addresses not in 191.0.0.0/8?

If not, I would ask that you check that outbound port 43/TCP is open on your firewall.

Are you running a ton of queries? You could be running into rate limiting which causes the lookup to wait and then retry.

Also, some notes:
- lookup_rdap() is the preferred method, and will get you better data than using lookup()
- Your script is duplicating some efforts provided by ipwhois.utils.ipv4_is_defined(): https://github.com/secynic/ipwhois/blob/master/ipwhois/net.py#L143

**Comment by robertjuric** [comment]
Thank you for the response. I was running lots of queries, however the stalls only appeared to be in the 191.0.0.0 /8. I did not have many from this network in my testing. 
I will look into modifying my code for lookup_rdap(). And I had need to figure out how to catch the exception for the is defined error, right now it just kills my script so I avoid them with some regex myself. I am a Python beginner, thank you again for the response.

**Comment by secynic** [comment]
Thanks. I have had issues in the past with LACNIC specifically, and throttling. I would try playing around with the retry_count and timeout parameters.

It is on my todo list to optimize those parameters. If you find that any configuration works better for LACNIC than the default, let me know.

You can catch IPDefinedError. You can also compare the error results against ipwhois.utils.IETF_RFC_REFERENCES for RFC links. This is something that I have not put in the documentation, but plan to soon.
